name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: "recursive"
      - name: Create ZIP archive
        run: zip -r RedwoodPlugins-${{ github.ref_name }}.zip . -x .git/\* .github/\* ThirdParty/**/.git
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: RedwoodPlugins-${{ github.ref_name }}.zip
