name: Release

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      PAT:
        description: 'Clone personal access token'
        required: true

jobs:
  release:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: "recursive"
          set-safe-directory: false
          repository: RedwoodMMO/Backend
          ref: ${{ github.event_name == 'workflow_call' && 'refs/heads/' || '' }}${{ github.event_name == 'push' && github.ref || inputs.branch }}
          token: ${{ secrets.PAT }}
      - name: Create ZIP archive
        run: 7z a -tzip RedwoodPlugins-${{ inputs.version }}.zip . -xr .git -xr .github
